[build]
  publish = "."

[[redirects]]
  from = "/index.php"
  to   = "/index.html"
  status = 301

[[redirects]]
  from = "/about.php"
  to   = "/about.html"
  status = 301

[[redirects]]
  from = "/projects.php"
  to   = "/projects.html"
  status = 301

[[redirects]]
  from = "/cv.php"
  to   = "/cv.html"
  status = 301

[[redirects]]
  from = "/skills.php"
  to   = "/skills.html"
  status = 301

[[redirects]]
  from = "/veille.php"
  to   = "/veille.html"
  status = 301

[[redirects]]
  from = "/contact.php"
  to   = "/contact.html"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options        = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy        = "strict-origin-when-cross-origin"
